### ISSUE TITLE
Serving files from Cloudfront when it shouldn't?

### ISSUE THREAD

**Issue by mike131** [nmendes/AmazonS3Cloudfront#1]
First, thank you so much for this plugin!

I am using this successfully for the most part but have some questions, as I need to try to make this work for my use.

The uploads to S3 and serving from cloudfront work fantastically, however I am having some issues.

In some templates, there are calls made such as $page->top_image->width(1280);
This then tries to serve from {cloudfronturl}/filename.1280x0.jpg
So what I want to accomplish is so that no matter what width it looks for, I can just serve {cloudfronturl}/filename.jpg without the weird appending.

Do you have any suggestions?

**Comment by nmendes** [comment]
Mike,

Thanks. Glad it is working for you. 
From what I understood from your message, you are getting the filename that ProcessWire uses for the image cropping. The plugin doesn't change the base name, it just appends a kind of timestamp so it can clear the cloudfront cache easily without you having to do it manually. 
So this is out of the scope of the plugin/module, I tried to keep things as close to the PW functioning as possible.

I think there is no way (If I understand your question correctly) to keep the base filename as with the call $page->top_image->width(1280) you are actually creating a copy of the filename.jpg with 1280px of width and it makes sense, as a copy, that the new images has a different name, hence the filename.1280x0.jpg. 

The only way is to use the image directly without cropping it via PW (cropping it before uploading it to PW) and call it directly.

**Comment by mike131** [comment]
Thank you @nmendes!

I realize now that I should've just been searching and removing the ->width() calls from the template.

Sorry, Processwire amateur.  :smile:
