### ISSUE TITLE
Uploading images in admin

### ISSUE THREAD

**Issue by mike131** [nmendes/AmazonS3Cloudfront#2]
After uploading images using the admin backend, it shows a broken image.

When I inspected the element containing the image preview in the admin page, I see that it is still looking to the site/assets/files folder on the server and not the cloudfront location (the image was successfully uploaded there).

Is this an issue with the module? I am pretty certain that this was working just fine before when I tested.

**Comment by nmendes** [comment]
Have you checked the "Use CloudFront to serve the assets" in the module configuration?

**Comment by mike131** [comment]
Yes, that option is checked.

**Comment by nmendes** [comment]
That's weird. It stopped working suddenly? I'm using it on live websites and never got any problem like that. May I suggest you to uninstall and install the module again using the same configuration?

**Comment by mike131** [comment]
I tried reinstallnig the plugin, but the preview I get in the admin still shows from the server:
![screen shot 2014-12-01 at 1 40 43 pm](https://cloud.githubusercontent.com/assets/3331540/5250993/bb46653e-795f-11e4-9304-35a96fdfa984.png)

**Comment by nmendes** [comment]
But all the other images are coming from Cloudfront? If the issue is only with that one, is that a different type of field on PW?

**Comment by mike131** [comment]
The issue seems to be occurring for any image I upload, whether it is a page, blog, etc.

From what I can see it seems to be a "standard" input field. 

EDIT: Yes all the images when I preview the page are coming from Cloudfront.

**Comment by nmendes** [comment]
So what you are saying is that in the admin the images are coming from the local assets and in the website itself the images are coming from Cloudfront, is this right?

**Comment by nmendes** [comment]
The plugin uses the local assets in the admin. Only in the website the content is fetched from Cloudfront/S3.

**Comment by mike131** [comment]
Sorry for leaving this open, thanks for your help!
